name: firebase_login_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  awesome_dialog: ^3.0.2
  cloud_firestore: ^4.6.0
  google_maps_flutter: ^2.2.5
  image_picker: ^0.8.7+3
  flutter_advanced_segment: ^3.0.2
  firebase_storage: ^11.2.1
  # flutter_clean_calendar: ^1.1.0
  flutter_calendar_carousel:
  flutter_time_picker_spinner: ^2.0.0
  fluttertoast: ^8.2.2
  animated_text_kit: ^4.2.2
  geolocator: ^9.0.2
  http: ^0.13.4
  firebase_messaging: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/images/tutor.png
    - assets/images/images/student.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
    # - family: Raleway
    #   fonts:
    #     - asset: assets/fonts/Raleway-ExtraLight.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
