// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHUWSrdUNkObBMWXIOvYpznpWYTEb35Go',
    appId: '1:913794925040:web:74bed25c3375b1808b1d35',
    messagingSenderId: '913794925040',
    projectId: 'flutter-log-in-app-b603e',
    authDomain: 'flutter-log-in-app-b603e.firebaseapp.com',
    storageBucket: 'flutter-log-in-app-b603e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdRMeYJz93rnLjGzEsd9ccEoPiJwFTm3w',
    appId: '1:913794925040:android:732435adafc6d4f18b1d35',
    messagingSenderId: '913794925040',
    projectId: 'flutter-log-in-app-b603e',
    storageBucket: 'flutter-log-in-app-b603e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfrYZz6-2JA0abGk9s_fcEGNvs23NJewU',
    appId: '1:913794925040:ios:a06bd5b0bea0b6928b1d35',
    messagingSenderId: '913794925040',
    projectId: 'flutter-log-in-app-b603e',
    storageBucket: 'flutter-log-in-app-b603e.appspot.com',
    iosClientId: '913794925040-7c1lc0nhqis4csfodtbcsigkeadlk0cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfrYZz6-2JA0abGk9s_fcEGNvs23NJewU',
    appId: '1:913794925040:ios:a06bd5b0bea0b6928b1d35',
    messagingSenderId: '913794925040',
    projectId: 'flutter-log-in-app-b603e',
    storageBucket: 'flutter-log-in-app-b603e.appspot.com',
    iosClientId: '913794925040-7c1lc0nhqis4csfodtbcsigkeadlk0cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginApp',
  );
}
